### ISSUE TITLE
The experiment setting for BMG

### ISSUE THREAD

**Issue by stevvwen** [MagiFeeney/Bootstrapped-Meta-Learning#1]
Hi,
Thanks so much for sharing your reproduction. I just wanna know what is your experiment setting for BMG. I got quite different results from the ones you on readme. The BMG now is worse than the baseline A2C.
One potential error that we found right now is in bmg.py line 24.
We think the code should be `loss, _, _ = self.controller.rollout(self.inner_model, self.outer_model)` 

![shaded-rew-step_bmg](https://github.com/MagiFeeney/Bootstrapped-Meta-Learning/assets/68338716/268d6b6b-b3fe-4484-b0b8-f814194f96be)

**Comment by MagiFeeney** [comment]
Thanks for pointing out the error. I will revise the code. Please check if the problem still exists. (btw, my time currently would not allow me to maintain the code as it has been conducted for a long time, but once I have available time I will re-check)

**Comment by stevvwen** [comment]
Thanks for replying. But I am still curious about what hyperparameter setting you used to generate the results you showed on the README.

**Comment by MagiFeeney** [comment]
The hyperparameters we use are the same as the script as we provided in the README, and the results of both MGRL and BMG only run once. It worth mentioning that our result is based on the initial release of the torchopt, whereas it has made a lot changes by far, so there may be some performance discrepancy.

**Comment by MagiFeeney** [comment]
As no further issue appears at this time, I will close it.
